### ISSUE TITLE
Almost there: Missing spots on the fractal

### ISSUE THREAD

**Issue by devarshku** [FransFaase/FractalJigsawPuzzle#4]
Hi, I am trying to generate a simple fractal. I have most of it working but need help in a couple of issues:

1.  **Missing circular white spots and incomplete ends**
For every fractal I generate, I end up with missing white circular spots across the canvas.
To demonstrate an example, from among the solutions generated with the following command - 
`./pianofrac gen_ec -con -range=2-3 -with_name | ./ExactCover | ./pianofrac normalize -minimal | ./pianofrac used_pieces | sort | uniq -c | sort`, 
I choose the following combination of pieces: 
`1,1,1,2,2,2,2,2,3,4,4,4,4,7,7,10`
as and input to: 
`./pianofrac svg -depth=1 -stroke_width=2 > t2.svg`
Given that github doesn't support svg files. I have uploaded it as a txt.
[t2.txt](https://github.com/FransFaase/FractalJigsawPuzzle/files/5615921/t2.txt)
What am I missing?

2. **Reduce complexity of the fractal**
In addition, I want to reduce the complexity of the fractal i.e. I want to have fewer lines within the same dimensions(or same side length). How do I go about it?

Thanks in advance :)

**Comment by FransFaase** [comment]
I have extended the Readme file with a description of which commands you should have used. Please let me know if it works now.

**Comment by devarshku** [comment]
Perfect! Now it works, thank you :)
I was confused with the solutions from the exacts cover solver and the puzzles.

**Comment by devarshku** [comment]
Perfect! Now it works, thank you :)
I was confused with the solutions from the exacts cover solver and the puzzles.
